pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "label=automerge"
      - check-success=Build Prod Image
      - check-success=Django tests (3.8)
      - check-success=Django tests (3.9)
      - check-success=Static checks
      - check-success=BI Validate
    actions:
      merge:
        method: squash
