---
version: '3'

services:
  web:
    extends:
      file: docker-compose.yaml
      service: web
    build:
      context: .
      dockerfile: scripts/ci-docker-image/Dockerfile
      args:
        - DJANGO_VERSION
        - PYTHON_VERSION
    command: test --verbosity=2 --keepdb

  web-init:
    extends:
      file: docker-compose.yaml
      service: web-init

  minio:
    extends:
      file: docker-compose.yaml
      service: minio


  minio-init:
    extends:
      file: docker-compose.yaml
      service: minio-init

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
