---
version: '3'

services:
  web:
    build:
      context: .
      args:
        - DJANGO_VERSION
        - PYTHON_VERSION
    command: bash -c "sleep 5 & coverage run manage.py test --verbosity=2 --keepdb"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: 'postgres://pola_app:pola_app@postgres/pola_app'

  postgres:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_USER: pola_app
      POSTGRES_PASSWORD: pola_app
      POSTGRES_DB: pola_app
