# Generated by Django 2.0.3 on 2018-05-27 06:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20171207_0215'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=['created_at'], name='product_pro_created_f272ea_brin', pages_per_range=16
            ),
        ),
    ]
