# Generated by Django 2.0.5 on 2018-06-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_brand'),
        ('product', '0009_auto_20180527_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='company.Brand',
                verbose_name='Marka produktu',
            ),
        ),
    ]
