# Generated by Django 3.1.2 on 2021-01-13 17:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20210113_1800'),
        ('product', '0011_auto_20201012_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='companies',
            field=models.ManyToManyField(related_name='companies', to='company.Company', verbose_name='Producenci'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(
                db_index=True,
                max_length=20,
                unique=True,
                validators=[django.core.validators.validate_integer],
                verbose_name='Kod',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='company',
                to='company.company',
                verbose_name='Producent',
            ),
        ),
    ]
