# Generated by Django 3.1.5 on 2021-01-17 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210113_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(
                db_index=True,
                max_length=20,
                unique=True,
                validators=[django.core.validators.validate_integer],
                verbose_name='Kod',
            ),
        ),
    ]
