# Generated by Django 3.2.10 on 2021-12-29 17:55

import django.contrib.postgres.indexes
import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20210215_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={
                'ordering': ['-created'],
                'permissions': (),
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={
                'ordering': ['-created'],
                'permissions': (),
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
            },
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_com_created_54f6ef_brin',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='brand',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name='modified'
            ),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created',
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name='created'
            ),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name='created'
            ),
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=['created'], name='company_com_created_b4a129_brin', pages_per_range=16
            ),
        ),
    ]
