# Generated by Django 3.2.16 on 2023-08-19 15:33

import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0026_alter_brand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logotype',
            field=models.ImageField(
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket_name='pola-app-ai-pics', querystring_auth=True, region_name='eu-central-1'
                ),
                upload_to='',
                verbose_name='Logotyp',
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='official_url',
            field=models.URLField(null=True, verbose_name='Link do strony firmy'),
        ),
    ]
