# Generated by Django 3.2.16 on 2023-12-15 20:19

import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0027_auto_20231121_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logotype',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket_name='pola-app-company-logotype',
                    default_acl=None,
                    querystring_auth=True,
                    region_name='eu-central-1',
                ),
                upload_to='logo/%Y/%m/%d',
                verbose_name='Logotyp',
            ),
        ),
    ]
