# Generated by Django 3.2.16 on 2023-11-13 07:53

import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0027_auto_20230819_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logotype',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket_name='pola-app-company-logotype', querystring_auth=True, region_name='eu-central-1'
                ),
                upload_to='logo/%Y/%m/%d',
                verbose_name='Logotyp',
            ),
        ),
        migrations.AlterField(
            model_name='company',
            name='official_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do strony firmy'),
        ),
    ]
