# Generated by Django 3.2.16 on 2024-03-22 16:26

import django_resized.forms
import storages.backends.s3
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0031_auto_20240107_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logotype',
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format='PNG',
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[None, 200],
                storage=storages.backends.s3.S3Storage(
                    bucket_name='pola-app-company-logotype', querystring_auth=False, region_name='eu-central-1'
                ),
                upload_to='brand-logotype/%Y/%m/%d',
                verbose_name='Logotyp',
            ),
        ),
    ]
