# Generated by Django 3.2.16 on 2024-06-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_alter_brand_logotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='website_url',
            field=models.CharField(default='example.pl', max_length=128, verbose_name='URL marki'),
        ),
    ]
