# Generated by Django 5.1.8 on 2025-11-08 09:16

import django_resized.forms
import storages.backends.s3
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_brand_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logotype',
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format='PNG',
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[None, 200],
                storage=storages.backends.s3.S3Storage(
                    bucket_name='pola-app-company-logotype',
                    default_acl=None,
                    querystring_auth=False,
                    region_name='eu-central-1',
                ),
                upload_to='logo/%Y/%m/%d',
                verbose_name='Logotyp',
            ),
        ),
    ]
