# Generated by Django 5.1.8 on 2025-11-08 09:16

import django_resized.forms
from django.db import migrations

import pola.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_brand_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logotype',
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format='PNG',
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[None, 200],
                storage=pola.storage_backends.CompanyLogotypeStorage(),
                upload_to='logo/%Y/%m/%d',
                verbose_name='Logotyp',
            ),
        ),
    ]
