# Generated by Django 1.11.8 on 2017-12-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_ai_pics_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={
                'ordering': ['-created_at'],
                'permissions': (('view_product', 'Can see all product'),),
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
    ]
