# Generated by Django 3.1.7 on 2021-09-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='companies',
        ),
    ]
