# Generated by Django 3.2.10 on 2021-12-29 17:55

import django.contrib.postgres.indexes
import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_companies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={
                'ordering': ['-created'],
                'permissions': (),
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_created_f272ea_brin',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name='modified'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name='created'
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=['created'], name='product_pro_created_f16120_brin', pages_per_range=16
            ),
        ),
    ]
