# Generated by Django 3.2.16 on 2023-01-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpc', '0002_alter_gpcbrick_code'),
        ('product', '0019_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gpc_brick',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='gpc.gpcbrick',
                verbose_name='GPC Brick',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='gs1_last_response',
            field=models.JSONField(null=True),
        ),
    ]
