# Generated by Django 3.2.16 on 2024-07-31 18:08

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20230110_2035'),
    ]

    operations = [VectorExtension()]
