# Generated by Django 5.1.8 on 2025-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20230110_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='replacements',
            field=models.ManyToManyField(blank=True, to='product.product', verbose_name='Zamienniki'),
        ),
    ]
