# Generated by Django 3.2.16 on 2024-08-07 15:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=512, editable=False, null=True),
        ),
    ]
