# Generated by Django 3.2.15 on 2022-11-07 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GPCSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Kod')),
                ('text', models.CharField(max_length=255, verbose_name='Nazwa kategorii')),
                ('definition', models.TextField(null=True, verbose_name='Nazwa kategorii')),
                ('active', models.BooleanField(null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa alternatywna')),
            ],
            options={
                'verbose_name': 'GPC Segment',
                'verbose_name_plural': 'GPC Segmenty',
                'db_table': 'gpc_segment',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='GPCFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Kod')),
                ('text', models.CharField(max_length=255, verbose_name='Nazwa rodziny')),
                ('definition', models.TextField(null=True, verbose_name='Opis rodziny')),
                ('active', models.BooleanField(null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa alternatywna')),
                (
                    'parent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='gpc.gpcsegment', verbose_name='Segment'
                    ),
                ),
            ],
            options={
                'verbose_name': 'GPC Rodzina',
                'verbose_name_plural': 'GPC Rodziny',
                'db_table': 'gpc_family',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='GPCClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Kod')),
                ('text', models.CharField(max_length=255, verbose_name='Nazwa klasy')),
                ('definition', models.TextField(null=True, verbose_name='Opis klasy')),
                ('active', models.BooleanField(null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa alternatywna')),
                (
                    'parent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='gpc.gpcfamily', verbose_name='Segment'
                    ),
                ),
            ],
            options={
                'verbose_name': 'GPC Klasa',
                'verbose_name_plural': 'GPC Klasy',
                'db_table': 'gpc_class',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='GPCBrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Kod')),
                ('text', models.CharField(max_length=255, verbose_name='Nazwa brick')),
                ('definition', models.TextField(null=True, verbose_name='Opis brick')),
                ('definitionExcludes', models.TextField(null=True, verbose_name='Opis wykluczeń')),
                ('active', models.BooleanField(null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa alternatywna')),
                (
                    'parent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='gpc.gpcclass', verbose_name='Class'
                    ),
                ),
            ],
            options={
                'verbose_name': 'GPC Brick',
                'verbose_name_plural': 'GPC Bricks',
                'db_table': 'gpc_brick',
                'ordering': ['-code'],
            },
        ),
    ]
