# Generated by Django 3.2.15 on 2022-11-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpcbrick',
            options={'ordering': ['-code'], 'verbose_name': 'GPC Brick', 'verbose_name_plural': 'GPC Bricks'},
        ),
        migrations.AlterModelOptions(
            name='gpcclass',
            options={'ordering': ['-code'], 'verbose_name': 'GPC Klasa', 'verbose_name_plural': 'GPC Klasy'},
        ),
        migrations.AlterModelOptions(
            name='gpcfamily',
            options={'ordering': ['-code'], 'verbose_name': 'GPC Rodzina', 'verbose_name_plural': 'GPC Rodziny'},
        ),
        migrations.AlterModelOptions(
            name='gpcsegment',
            options={'ordering': ['-code'], 'verbose_name': 'GPC Segment', 'verbose_name_plural': 'GPC Segmenty'},
        ),
    ]
