# Generated by Django 3.2.16 on 2023-01-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpcbrick',
            name='code',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Kod'),
        ),
    ]
