# Generated by Django 3.2.15 on 2022-11-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpc', '0002_auto_20221103_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpcbrick',
            name='alias',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa alternatywna'),
        ),
        migrations.AddField(
            model_name='gpcclass',
            name='alias',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa alternatywna'),
        ),
        migrations.AddField(
            model_name='gpcfamily',
            name='alias',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa alternatywna'),
        ),
        migrations.AddField(
            model_name='gpcsegment',
            name='alias',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa alternatywna'),
        ),
    ]
