# Generated by Django 3.2.15 on 2022-11-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpc', '0003_auto_20221105_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpcbrick',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa alternatywna'),
        ),
        migrations.AlterField(
            model_name='gpcclass',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa alternatywna'),
        ),
        migrations.AlterField(
            model_name='gpcfamily',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa alternatywna'),
        ),
        migrations.AlterField(
            model_name='gpcsegment',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa alternatywna'),
        ),
    ]
