SELECT
    COUNT(*) request_total,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 day') request_day,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 week') request_week,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 month') request_month,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '3 month') request_3_month,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '6 month') request_6_month,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 day' AND was_590 = true) request_day_was_590,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 week' AND was_590 = true) request_week_was_590,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 month' AND was_590 = true) request_month_was_590,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '3 month' AND was_590 = true) request_3_month_was_590,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '6 month' AND was_590 = true) request_6_month_was_590,
    COUNT(*) FILTER(WHERE was_590 = true) request_total_was_590,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 day' AND "was_plScore" = true) request_day_was_plScore,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 week' AND "was_plScore" = true) request_week_was_plScore,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 month' AND "was_plScore" = true) request_month_was_plScore,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '3 month' AND "was_plScore" = true) request_3_month_was_plScore,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '6 month' AND "was_plScore" = true) request_6_month_was_plScore,
    COUNT(*) FILTER(WHERE "was_plScore" = true) request_total_was_plScore,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 day' AND was_verified = true) request_day_was_verified,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 week' AND was_verified = true) request_week_was_verified,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '1 month' AND was_verified = true) request_month_was_verified,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '3 month' AND was_verified = true) request_3_month_was_verified,
    COUNT(*) FILTER(WHERE timestamp > NOW() - INTERVAL '6 month' AND was_verified = true) request_6_month_was_verified,
    COUNT(*) FILTER(WHERE was_verified = true) request_total_was_verified,
    COUNT(DISTINCT client) uq_user_total,
    COUNT(DISTINCT client) FILTER(WHERE timestamp > NOW() - INTERVAL '1 day') uq_user_day,
    COUNT(DISTINCT client) FILTER(WHERE timestamp > NOW() - INTERVAL '1 week') uq_user_week,
    COUNT(DISTINCT client) FILTER(WHERE timestamp > NOW() - INTERVAL '1 month') uq_user_month,
    COUNT(DISTINCT client) FILTER(WHERE timestamp > NOW() - INTERVAL '3 month') uq_user_3_month,
    COUNT(DISTINCT client) FILTER(WHERE timestamp > NOW() - INTERVAL '6 month') uq_user_6_month
FROM
    {{ source('public', 'pola_query') }}
