# Generated by Django 1.11.8 on 2017-12-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pics', '0003_aipics_is_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiattachment',
            options={
                'permissions': (('view_aiattachment', 'Can see all AIAttachment'),),
                'verbose_name': "AIPics's attachment",
                'verbose_name_plural': "AIPics's attachments",
            },
        ),
        migrations.AlterModelOptions(
            name='aipics',
            options={
                'permissions': (('view_aipics', 'Can see all AIPics'),),
                'verbose_name': 'AIPics',
                'verbose_name_plural': 'AIPics',
            },
        ),
    ]
