# Generated by Django 2.0.2 on 2020-10-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pics', '0005_auto_20180527_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiattachment',
            options={
                'permissions': (),
                'verbose_name': "AIPics's attachment",
                'verbose_name_plural': "AIPics's attachments",
            },
        ),
        migrations.AlterModelOptions(
            name='aipics',
            options={'permissions': (), 'verbose_name': 'AIPics', 'verbose_name_plural': 'AIPics'},
        ),
    ]
