# Generated by Django 3.1.7 on 2021-10-03 03:56

import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pics', '0009_auto_20210117_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiattachment',
            name='attachment',
            field=models.FileField(
                storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='pola-app-ai-pics', querystring_auth=True),
                upload_to='ai/%Y/%m/%d',
                verbose_name='File',
            ),
        ),
    ]
