# Generated by Django 3.1.6 on 2021-02-15 17:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pics', '0009_auto_20210117_0154'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aipics',
            name='ai_pics_aip_created_9179cd_brin',
        ),
        migrations.RenameField(
            model_name='aipics',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddIndex(
            model_name='aipics',
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=['created'], name='ai_pics_aip_created_96e607_brin', pages_per_range=16
            ),
        ),
    ]
