language: node_js
node_js:
  - 11.15.0

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves fpr cypress tests
      - libgconf-2-4

before_install:
  - echo do pre-install things here...

install:
  - node --version
  - pwd
  - npm install

before_script:
  - echo do pre-scripts things here...

script:
  ## Run unit tests
  - npm run test-once

  ## Runs e2e cypress + cucmber tests
  - npm start & wait-on http://localhost:8000
  - npm run e2e-headless

# - do your other automated tests here!

after_script:
  - echo ran script
after_success:
  - npm run build

  # - do your deploy commands here!
  - echo Welp, that's another happy CI deploy!

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  edge: true
  on:
    branch: v1.0.1-release

matrix:
  fast_finish: true

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
