# Generated by Django 2.0.3 on 2018-05-27 06:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pics', '0004_auto_20171207_0215'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aipics',
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=['created_at'], name='ai_pics_aip_created_9179cd_brin', pages_per_range=16
            ),
        ),
    ]
