# Generated by Django 3.1.5 on 2021-01-17 00:09

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ai_pics', '0006_auto_20201012_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiattachment',
            name='attachment',
            field=models.FileField(
                storage=storages.backends.gcloud.GoogleCloudStorage(bucket_name='pola-app-ai-local'),
                upload_to='ai/%Y/%m/%d',
                verbose_name='File',
            ),
        ),
    ]
