# Generated by Django 3.1.5 on 2021-01-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pics', '0008_auto_20210117_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipics',
            name='flash_used',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='aipics',
            name='is_valid',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='aipics',
            name='was_portrait',
            field=models.BooleanField(null=True),
        ),
    ]
