# Generated by Django 3.2.10 on 2022-02-05 09:33

from django.db import migrations, models

import pola.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ('ai_pics', '0011_auto_20211229_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiattachment',
            name='attachment',
            field=models.FileField(
                storage=pola.storage_backends.AiPicsStorage(),
                upload_to='ai/%Y/%m/%d',
                verbose_name='File',
            ),
        ),
    ]
