# syntax=docker/dockerfile:1.14.0
# check=error=true;experimental=all

ARG BASE_IMAGE=ghcr.io/klubjagiellonski/pola-backend/pola-backend:latest

# hadolint ignore=DL3006
FROM --platform=linux/amd64 ${BASE_IMAGE}

CMD ["bash", "-c", "./manage.py migrate --no-input && ./manage.py collectstatic --no-input"]
