# Generated by Django 2.0.5 on 2018-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_friend',
            field=models.BooleanField(
                choices=[(True, 'Tak'), (False, 'Nie')], default=False, verbose_name='Przyjaciel Poli'
            ),
        ),
    ]
