# Generated by Django 2.0.2 on 2019-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_company_is_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nazwa dla użytkownika'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, verbose_name='Nazwa (pobrana z ILiM)'
            ),
        ),
        migrations.AlterField(
            model_name='company',
            name='official_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa rejestrowa'),
        ),
    ]
