# Generated by Django 2.0.2 on 2020-10-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20190516_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={
                'ordering': ['-created_at'],
                'permissions': (),
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={
                'ordering': ['-created_at'],
                'permissions': (),
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
            },
        ),
    ]
