# Generated by Django 3.1.5 on 2021-01-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_auto_20210116_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=False,
                verbose_name='Nazwa (pobrana z ILiM)',
            ),
        ),
    ]
