# Generated by Django 3.1.7 on 2021-05-19 13:07

import django.db.models.deletion
from django.db import migrations, models

import company.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20210215_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'name',
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True, verbose_name='Nazwa (pobrana z ILiM)'
                    ),
                ),
                (
                    'official_name',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa rejestrowa'),
                ),
                ('common_name', models.CharField(blank=True, max_length=255, verbose_name='Nazwa dla użytkownika')),
                (
                    'plCapital',
                    company.models.IntegerRangeField(blank=True, null=True, verbose_name='Udział polskiego kapitału'),
                ),
                (
                    'plWorkers',
                    company.models.IntegerRangeField(
                        blank=True,
                        choices=[(0, '0 - Nie produkuje w Polsce'), (100, '100 - Produkuje w Polsce')],
                        null=True,
                        verbose_name='Miejsce produkcji',
                    ),
                ),
                (
                    'plRnD',
                    company.models.IntegerRangeField(
                        blank=True,
                        choices=[
                            (0, '0 - Nie tworzy miejsc pracy w BiR Polsce'),
                            (100, '100 - Tworzy miejsca pracy w BiR w Polsce'),
                        ],
                        null=True,
                        verbose_name='Miejsca pracy w BiR w Polsce',
                    ),
                ),
                (
                    'plRegistered',
                    company.models.IntegerRangeField(
                        blank=True,
                        choices=[
                            (0, '0 - Firma zarejestrowana za granicą'),
                            (100, '100 - Firma zarejestrowana w Polsce'),
                        ],
                        null=True,
                        verbose_name='Miejsce rejestracji',
                    ),
                ),
                (
                    'plNotGlobEnt',
                    company.models.IntegerRangeField(
                        blank=True,
                        choices=[
                            (0, '0 - Firma jest częścią zagranicznego koncernu'),
                            (100, '100 - Firma nie jest częścią zagranicznego koncernu'),
                        ],
                        null=True,
                        verbose_name='Struktura kapitałowa',
                    ),
                ),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis grupy kapitałowej')),
                ('sources', models.TextField(blank=True, null=True, verbose_name='Źródła')),
                (
                    'verified',
                    models.BooleanField(
                        choices=[(True, 'Tak'), (False, 'Nie')], default=False, verbose_name='Dane zweryfikowane'
                    ),
                ),
                (
                    'Editor_notes',
                    models.TextField(
                        blank=True, null=True, verbose_name='Notatki redakcji (nie pokazujemy użytkownikom)'
                    ),
                ),
                (
                    'plCapital_notes',
                    models.TextField(blank=True, null=True, verbose_name='Więcej nt. udziału polskiego kapitału'),
                ),
                (
                    'plWorkers_notes',
                    models.TextField(blank=True, null=True, verbose_name='Więcej nt. miejsca produkcji'),
                ),
                ('plRnD_notes', models.TextField(blank=True, null=True, verbose_name='Więcej nt. miejsc pracy w BiR')),
                (
                    'plRegistered_notes',
                    models.TextField(blank=True, null=True, verbose_name='Więcej nt. miejsca rejestracji'),
                ),
                (
                    'plNotGlobEnt_notes',
                    models.TextField(blank=True, null=True, verbose_name='Więcej nt. struktury kapitałowej'),
                ),
                (
                    'nip',
                    models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='NIP/Tax ID'),
                ),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                (
                    'is_friend',
                    models.BooleanField(
                        choices=[(True, 'Tak'), (False, 'Nie')], default=False, verbose_name='Przyjaciel Poli'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Grupa kapitałowa',
                'verbose_name_plural': 'Grupy kapitałowe',
                'ordering': ['-created_at'],
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='capital_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='company.capitalgroup',
                verbose_name='Grupa kapitałowa',
            ),
        ),
    ]
