# Generated by Django 2.0 on 2017-12-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pola', '0004_auto_20151029_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(name='query', options={'get_latest_by': 'timestamp'},),
    ]
