# Generated by Django 2.0.3 on 2018-05-27 06:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pola', '0006_auto_20180527_0840'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stats',
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=['calculated_at'], name='pola_stats_calcula_5c5f00_brin', pages_per_range=16
            ),
        ),
    ]
