# Generated by Django 3.2.12 on 2022-04-17 20:02

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pola', '0007_auto_20180527_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('text', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=['timestamp'], name='pola_search_timesta_5b83df_brin', pages_per_range=64
            ),
        ),
    ]
