# Generated by Django 3.2.16 on 2024-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pola', '0008_auto_20220417_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'donate_url',
                    models.URLField(
                        default='https://www.pola-app.pl/1-5-podatku-na-aplikacje-pola',
                        max_length=100,
                        verbose_name='URL Donacji',
                    ),
                ),
                (
                    'donate_text',
                    models.CharField(
                        default='1,5% podatku na aplikację Pola?', max_length=255, verbose_name='Tekst Donacji'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Konfiguracja aplikacji',
            },
        ),
    ]
