# Generated by hand for adding default_banner to AppConfiguration

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pola', '0009_appconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='default_banner',
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format='PNG',
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1200, None],
                upload_to='banner/%Y/%m/%d',
                verbose_name='Domyślny baner',
            ),
        ),
    ]
