# Generated by hand to add banner_url to AppConfiguration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pola', '0010_appconfiguration_default_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='banner_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Banner URL'),
        ),
    ]
