# Generated by hand to alter upload_to for default_banner

import django_resized.forms
from django.db import migrations

import pola.models


class Migration(migrations.Migration):

    dependencies = [
        ('pola', '0011_appconfiguration_banner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='default_banner',
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format='PNG',
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1200, None],
                upload_to=pola.models.app_default_banner_upload_to,
                verbose_name='Domyślny baner',
            ),
        ),
    ]
