# Generated by Django 1.11.8 on 2017-12-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20151031_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={
                'get_latest_by': 'created_at',
                'ordering': ['-created_at'],
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
