# Generated by Django 3.1.7 on 2021-10-03 03:56

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0008_auto_20201012_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(
                storage=storages.backends.gcloud.GoogleCloudStorage(
                    bucket_name='pola-app-backend', querystring_auth=True
                ),
                upload_to='reports/%Y/%m/%d',
                verbose_name='File',
            ),
        ),
    ]
