# Generated by Django 3.2.10 on 2022-02-05 10:09

from django.db import migrations, models

import pola.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0010_auto_20211229_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(
                storage=pola.storage_backends.BackendMediaStorage(),
                upload_to='reports/%Y/%m/%d',
                verbose_name='File',
            ),
        ),
    ]
