# Generated by Django 3.2.10 on 2022-02-05 10:09

import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20211229_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket_name='pola-app-backend', querystring_auth=True, region_name='eu-central-1'
                ),
                upload_to='reports/%Y/%m/%d',
                verbose_name='File',
            ),
        ),
    ]
