---
config:
  send_anonymous_usage_stats: false
  use_colors: true

pola_app_postgres:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: "{{ env_var('PGHOST') }}"
      port: "{{ env_var('PGPORT') | as_number }}"
      user: "{{ env_var('PGUSER') }}"
      pass: "{{ env_var('PGPASS') }}"
      schema: "public"
      dbname: "{{ env_var('PGDATABASE') }}"

    prod:
      type: postgres
      threads: 4
      host: "{{ env_var('PGHOST') }}"
      port: "{{ env_var('PGPORT') | as_number }}"
      user: "{{ env_var('PGUSER') }}"
      pass: "{{ env_var('PGPASSWORD') }}"
      schema: "public"
      dbname: "{{ env_var('PGDATABASE') }}"

  target: dev
