name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 * * * *'

  workflow_dispatch:

  check_suite:
    types:
      - completed

  status: {}

jobs:
  automerge:
    if: github.repository == 'KlubJagiellonski/pola-backend'
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: 'squash'
          MERGE_FORKS: 'false'
