---
name: BI Build
on:
  #  schedule:
  #    - cron: '28 0 * * 1'
  push:
    branches: ['master', 'prod']
  pull_request:
    branches: ['master']
    paths:
      - 'pola-bi/**'
      - 'scripts/**'
      - 'requirements/bi.txt'

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_ORGANIZATION: ${{ github.repository_owner }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bi-job:
    name: "BI job"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: "Login to Github Docker Registry"
        run: ./scripts/docker_login_github.sh
      - name: "Copy .env.example to .env"
        run: cp .env.example .env
      - name: "Build image"
        run: |
          # Build BI image
          ./scripts/bi-docker-image/build_image.sh
          # Verify BI image
          ./scripts/bi-docker-image/verify_image.sh
      - name: "Push image (push)"
        if: github.event_name == 'push'
        run: ./scripts/bi-docker-image/push_image.sh

  static-checks:
    name: "Static checks"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Run static checks"
        uses: pre-commit/action@v2.0.0
