---
name: CI Build
on:
  schedule:
    - cron: '28 0 * * 1'
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  django-tests:
    name: "Django tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.5", "3.6", "3.7", "3.8"]
        django_version: ["2.0.2"]
    env:
      PYTHON_VERSION: ${{ matrix.python_version }}
      DJANGO_VERSION: ${{ matrix.django_version }}
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
      - name: "Build images"
        run: docker-compose -f docker-compose-ci.yaml build
      - name: "Run tests"
        run: |
          docker-compose -f docker-compose-ci.yaml up -d postgres
          docker-compose -f docker-compose-ci.yaml run web /app/manage.py test --verbosity=2 --keepdb

  static-checks:
    name: "Static checks"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: "Run static checks"
        uses: pre-commit/action@v2.0.0
