name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Enable colors in CLI apps.
  # 3 - Truecolor support (16 million colors)
  # https://www.npmjs.com/package/chalk#chalksupportscolor
  FORCE_COLOR: 3
  AWS_BUCKET_NAME: kj-pola-app-web-preview

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Set deployment status
      uses: pbrandone/create-status-action@master
      if: github.repository == 'KlubJagiellonski/pola-web' && github.event_name == 'pull_request' && github.event.sender.type == 'User'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        state: pending
        description: Preparing deploy preview
        context: Deploy Preview URL
    - name: "Set public URL"
      if: github.repository == 'KlubJagiellonski/pola-web' && github.event_name == 'pull_request' && github.event.sender.type == 'User'
      run: |
        BASE_URL="http://${AWS_BUCKET_NAME}.s3-website.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com"
        PREVIEW_DIR="$(echo "${GITHUB_HEAD_REF}" | tr -c '[:alnum:]._-' '-')"
        PUBLIC_URL="${BASE_URL}/${PREVIEW_DIR}"
        echo "PREVIEW_DIR=${PREVIEW_DIR}" >> $GITHUB_ENV
        echo "PUBLIC_URL=${PUBLIC_URL}" >> $GITHUB_ENV
    - name: "Set public URL"
      if: github.repository == 'KlubJagiellonski/pola-web' && github.event_name == 'push'
      run: |
        echo 'PUBLIC_URL=https://klubjagiellonski.github.io/pola-web/' >> $GITHUB_ENV
    - name: 🗂 Checkout
      uses: actions/checkout@v2
    - name: 🟢 Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - name: 🗂 Cache npm files
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: |
          ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: 🟢 Install dependencies
      run: npm ci
    # - name: 🔎 Run the tests
      # run: npm test -- --coverage
    - name: 🔧 Build app
      run: npm run build
    - name: 🚀 Upload app as artifact
      uses: actions/upload-artifact@v2
      if: github.event_name == 'pull_request'
      with:
        name: app
        path: ./public
        if-no-files-found: error
    - name: 🚀 Deploy app on gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: github.repository == 'KlubJagiellonski/pola-web' && github.event_name == 'push'
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: ./public  # The folder the action should deploy.
        clean: true  # Automatically remove deleted files from the deploy branch.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: github.repository == 'KlubJagiellonski/pola-web' && github.event_name == 'pull_request' && github.event.sender.type == 'User'
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: "Upload preview to AWS S3"
      if: github.repository == 'KlubJagiellonski/pola-web' && github.event_name == 'pull_request' && github.event.sender.type == 'User'
      run: aws s3 sync --delete ./public/ "s3://${AWS_BUCKET_NAME}/${PREVIEW_DIR}"
    - name: Set success deployment status
      if: success() && github.repository == 'KlubJagiellonski/pola-web' && github.event_name == 'pull_request' && github.event.sender.type == 'User'
      uses: pbrandone/create-status-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        state: success
        description: Deploy preview ready!
        url: ${{ env.PUBLIC_URL }}
        context: Deploy Preview URL
    - name: Set failed deployment status
      if: failure() && github.repository == 'KlubJagiellonski/pola-web' && github.event_name == 'pull_request' && github.event.sender.type == 'User'
      uses: pbrandone/create-status-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        state: failure
        description: Failed to deploy preview
        context: Deploy Preview URL
