name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          heroku pg:backups:capture --app pola-app
          heroku pg:backups:download --app pola-app --output /tmp/latest.dump
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Clear volumes
        run: docker-compose down --volumes
      - name: Starts PostgresSQL
        run: docker-compose up postgres
      - name: Copy .env.example to .env
        run: cp .env.example .env
      - name: Load production dump
        run: |
          docker cp /tmp/latest.dump pola-backend_postgres_1:/tmp/latest.dump;
          docker exec \
            -ti \
            pola-backend_postgres_1 \
            pg_restore \
              --verbose \
              --clean \
              --no-acl \
              --no-owner \
              -h localhost \
              -U pola_app \
              -d pola_app /tmp/latest.dump
      - name: Migrate database
        run: docker-compose run web /app/manage.py migrate
      - name: Remove all data
        run: |
          rm /tmp/latest.dump;
          docker-compose down --volumes
