name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_ORGANIZATION: ${{ github.repository_owner }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          heroku pg:backups:capture --app pola-app
          heroku pg:backups:download --app pola-app --output /tmp/latest.dump
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Login to Github Docker Registry
        run: ./scripts/docker_login_github.sh
      - name: Copy .env.example to .env
        run: cp .env.example .env
      - run: docker images
      - name: Build image
        run: |
          # Build Django CI image
          ./scripts/ci-docker-image/build_image.sh
          # Verify CI image
          ./scripts/ci-docker-image/verify_image.sh
      - name: Clear volumes
        run: docker-compose down --volumes
      - name: Starts PostgresSQL
        run: docker-compose up --detach --no-deps postgres
      - name: Load production dump
        run: |
          set -x;
          docker cp /tmp/latest.dump pola-backend_postgres_1:/tmp/latest.dump;
          docker exec \
            -i \
            pola-backend_postgres_1 \
            pg_restore \
              --verbose \
              --clean \
              --no-acl \
              --no-owner \
              -h localhost \
              -U pola_app \
              -d pola_app /tmp/latest.dump || \
          docker exec \
            -i \
            pola-backend_postgres_1 \
            pg_restore \
              --verbose \
              --clean \
              --no-acl \
              --no-owner \
              -h localhost \
              -U pola_app \
              -d pola_app /tmp/latest.dump
      - name: Migrate database
        run: docker-compose run --no-deps --rm web /app/manage.py migrate
      - name: Remove all data
        run: |
          set -x;
          rm /tmp/latest.dump;
          docker-compose down --volumes
